spring:
  application:
    name: thenx-generator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: medv
    password: '@w-(*102Y613}+MySQL'
    url: jdbc:mysql://10.168.11.20:7205/quality?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: generator-pool
mybatis:
  mapper-locations: classpath:mapper/*.xml
